version: '2'
services:
  web:
    build: .
    command: bundle exec puma -p 3000 -e development
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app